[[plugins]]
repo = 'Shougo/dein.vim'


# ---------------------------------------------
# appearance
# ---------------------------------------------

[[plugins]]
repo = 'yamasy1549/gochiusa.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'


# ---------------------------------------------
# edit
# ---------------------------------------------

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo = 'scrooloose/nerdcommenter'


# ---------------------------------------------
# others
# ---------------------------------------------

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'

[[plugins]]
repo = 'tpope/vim-obsession'
