[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'


# ---------------------------------------------
# appearance
# ---------------------------------------------

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'


# ---------------------------------------------
# edit
# ---------------------------------------------

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'tpope/vim-endwise'


# ---------------------------------------------
# syntax
# ---------------------------------------------

# [[plugins]]
# repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'tpope/vim-markdown'

[[plugins]]
repo = 'sudar/vim-arduino-syntax'

[[plugins]]
repo = 'digitaltoad/vim-jade'

[[plugins]]
repo = 'digitaltoad/vim-pug'

[[plugins]]
repo = 'leafgarland/typescript-vim'


# ---------------------------------------------
# others
# ---------------------------------------------

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'

[[plugins]]
repo = 'basyura/unite-rails'

[[plugins]]
repo = 'tpope/vim-rails'

# [[plugins]]
# repo = 'tpope/vim-obsession'
